### ISSUE TITLE
Does not work with pnpm

### ISSUE THREAD

**Issue by eshaham** [aiji42/remix-esbuild-override#27]
It seems like the patching doesn't work properly when using `pnpm` as the package manager.
Should be fairly easy to re-produce - take one of the samples you have (we're using mantine).
Steps to reproduce:

* Remove `node_modules` folder
* Install `pnpm` globally
* Run `pnpm install`

I also reproduced the problem in this repo: https://github.com/eshaham/remix-esbuild-override-pnpm

**Comment by tedbyron** [comment]
I'm also having issues with pnpm, I tried the mantine example with the `Buffer` polyfill but I still get `ReferenceError: Buffer is not defined` when I run miniflare

**Comment by aiji42** [comment]
@eshaham 
In the repository you shared, the problem was resolved by either deleting the `esbuild` in `package.json` or matching the version with `@remix-run/dev`'s (v0.14.22).

```json
"devDependencies": {
    "@cloudflare/workers-types": "^3.10.0",
    "@esbuild-plugins/node-globals-polyfill": "^0.1.1",
    "@remix-run/dev": "^1.6.0",
    "@remix-run/eslint-config": "^1.6.0",
    "@types/react": "^17.0.45",
    "@types/react-dom": "^17.0.17",
    "esbuild": "0.14.22", // or remove
    "eslint": "^8.15.0",
    "npm-run-all": "^4.1.5",
    "remix-esbuild-override": "^3.0.4",
    "typescript": "^4.6.4",
    "wrangler": "beta"
  },
```

**Comment by aiji42** [comment]
@tedbyron If you share your repository with me, I may be able to help you solve your problem.

**Comment by iDVB** [comment]
@aiji42 I have remix-esbuild-override "building" ok with `pnpm` but our issue still persists. 
Using this as a guide does not work for us. 
https://mortenbarklund.com/blog/styled-components-remix/
